"""GRPO rollouts are generated by a colocated vLLM engine that stops at the suite's
stop string (transfer-rulings T21). Everything here runs on CPU: the GRPOConfig is
built by a pure helper, and the trainer is faked."""
import json
import os
from pathlib import Path

import pytest

from amenability.eval.passk import PASSK_MAX_TOKENS, sampling_kwargs, shutdown_vllm_engine
from amenability.suites.base import ANSWER_STOP, TaskItem
from amenability.training.grpo import (
    GENERATION_BACKEND,
    MAX_COMPLETION_LENGTH,
    PROMPTS_PER_STEP,
    VLLM_ENV_KEYS,
    VLLM_GPU_MEMORY_UTILIZATION,
    VLLM_MAX_MODEL_LENGTH,
    GRPOSpec,
    build_grpo_config_kwargs,
    check_fits_vllm_context,
    run_grpo,
)


def _items(n=2):
    return [
        TaskItem(task_id=f"t/{i}", suite="s", prompt=f"p{i}", answer="1", difficulty=0)
        for i in range(n)
    ]


def _spec(tmp_path, stop):
    return GRPOSpec(
        model_path="m", model_key="k", items=_items(), verify_fn=lambda i, c: True,
        max_steps=60, num_generations=8, learning_rate=1e-6, beta=0.04,
        temperature=1.0, seed=3, output_dir=str(tmp_path / "out"), save_steps=None,
        stop=stop,
    )


def test_probe_suite_config_uses_colocated_vllm_with_the_stop(tmp_path):
    kw = build_grpo_config_kwargs(_spec(tmp_path, ANSWER_STOP))
    assert kw["use_vllm"] is True
    assert kw["vllm_mode"] == "colocate"
    assert kw["generation_kwargs"] == {
        "stop": ["</answer>"],
        "include_stop_str_in_output": True,
    }


def test_gsm8k_config_uses_colocated_vllm_without_a_stop(tmp_path):
    kw = build_grpo_config_kwargs(_spec(tmp_path, None))
    assert kw["use_vllm"] is True
    assert kw["vllm_mode"] == "colocate"
    assert kw["generation_kwargs"] is None


@pytest.mark.parametrize("stop", [ANSWER_STOP, None])
def test_generation_kwargs_never_carry_a_per_request_seed(tmp_path, stop):
    # In colocate mode TRL submits each prompt num_generations times with n=1. A
    # per-request seed would give every copy the same random stream, so all eight
    # completions in a group would be identical and every advantage zero.
    gen = build_grpo_config_kwargs(_spec(tmp_path, stop))["generation_kwargs"] or {}
    assert "seed" not in gen


def test_vllm_memory_settings(tmp_path):
    kw = build_grpo_config_kwargs(_spec(tmp_path, ANSWER_STOP))
    assert kw["vllm_gpu_memory_utilization"] == VLLM_GPU_MEMORY_UTILIZATION == 0.3
    assert kw["vllm_enable_sleep_mode"] is True
    assert kw["vllm_max_model_length"] == VLLM_MAX_MODEL_LENGTH == 2048
    assert kw["vllm_tensor_parallel_size"] == 1


def test_the_loss_is_not_reweighted_by_vllm_importance_sampling(tmp_path):
    # TRL defaults this to True when use_vllm is set, which multiplies each
    # sequence's loss by a vLLM-vs-trainer likelihood ratio and drops sequences
    # whose ratio exceeds 3. The transformers path had no such term.
    kw = build_grpo_config_kwargs(_spec(tmp_path, ANSWER_STOP))
    assert kw["vllm_importance_sampling_correction"] is False


def test_backend_switch_leaves_every_protocol_quantity_unchanged(tmp_path):
    from trl import GRPOConfig

    cfg = GRPOConfig(**build_grpo_config_kwargs(_spec(tmp_path, ANSWER_STOP)))
    # Pinned (transfer-rulings T22), no longer TRL's default of 512.
    assert cfg.max_completion_length == 768
    assert cfg.learning_rate == 1e-6
    assert cfg.beta == 0.04
    assert cfg.temperature == 1.0
    assert cfg.num_generations == 8
    assert cfg.max_steps == 60
    assert cfg.per_device_train_batch_size == 8
    assert cfg.gradient_accumulation_steps == PROMPTS_PER_STEP
    assert cfg.seed == 3
    # Sampling distribution as on the transformers path: no top-p, top-k or
    # min-p filter, no repetition penalty.
    assert cfg.top_p == 1.0
    assert cfg.top_k == 0
    assert cfg.min_p is None
    assert cfg.repetition_penalty == 1.0
    # One generation per optimiser step, one optimisation pass per generation.
    assert cfg.steps_per_generation == PROMPTS_PER_STEP
    assert cfg.num_iterations == 1
    assert cfg.generation_kwargs == {"stop": ["</answer>"], "include_stop_str_in_output": True}


def test_completion_cap_is_pinned_to_the_passk_budget(tmp_path):
    # Transfer-rulings T22: GRPO rollouts get the same token budget as the pre- and
    # post-eval. At TRL's default of 512, 70% of Qwen2.5-0.5B's smoke rollouts were
    # cut before </answer> and scored 0, though the same model had 768 at pre-eval.
    kw = build_grpo_config_kwargs(_spec(tmp_path, ANSWER_STOP))
    assert kw["max_completion_length"] == MAX_COMPLETION_LENGTH == 768
    assert MAX_COMPLETION_LENGTH == PASSK_MAX_TOKENS
    assert sampling_kwargs(8, 1.0, 0, ANSWER_STOP)["max_tokens"] == MAX_COMPLETION_LENGTH


def test_context_check_accepts_the_probe_budget():
    check_fits_vllm_context(max_prompt_tokens=250, max_completion_length=MAX_COMPLETION_LENGTH)


def test_context_holds_the_longest_probe_prompt_plus_the_cap():
    # Prompts are counted in characters here, an upper bound on tokens for these
    # ASCII prompts, so the check holds for every tokenizer.
    from amenability.suites.catalog import PROBE_SUITES

    longest = max(
        len(it.prompt) for s in PROBE_SUITES.values() for it in s.generate(300, 0)
    )
    check_fits_vllm_context(max_prompt_tokens=longest, max_completion_length=MAX_COMPLETION_LENGTH)


def test_context_check_rejects_a_prompt_that_would_shorten_completions():
    with pytest.raises(ValueError, match="vllm_max_model_length"):
        check_fits_vllm_context(
            max_prompt_tokens=VLLM_MAX_MODEL_LENGTH - MAX_COMPLETION_LENGTH + 1,
            max_completion_length=MAX_COMPLETION_LENGTH,
        )


class _Core:
    def __init__(self, log):
        self.log = log

    def shutdown(self):
        self.log.append("shutdown")


class _LLM:
    def __init__(self, log):
        self.llm_engine = type("E", (), {"engine_core": _Core(log)})()


def test_shutdown_vllm_engine_shuts_the_engine_core_down():
    log = []
    shutdown_vllm_engine(_LLM(log))
    assert log == ["shutdown"]


def test_shutdown_vllm_engine_tolerates_an_object_without_an_engine():
    shutdown_vllm_engine(object())
    shutdown_vllm_engine(None)


def test_run_grpo_shuts_down_the_colocated_engine_and_restores_the_environment(
    tmp_path, monkeypatch
):
    # TRL's colocate init writes RANK/LOCAL_RANK/WORLD_SIZE/MASTER_*, and vLLM's
    # external_launcher backend writes VLLM_ENABLE_V1_MULTIPROCESSING=0. Left in
    # place, the post-eval's LLM would run in-process instead of in an EngineCore
    # subprocess like the pre-eval did.
    for key in VLLM_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)
    monkeypatch.setenv("MASTER_ADDR", "node7")
    log = []

    class Trainer:
        def __init__(self, **kw):
            self.model = None
            self.vllm_generation = type("G", (), {"llm": _LLM(log)})()

        def train(self):
            os.environ["VLLM_ENABLE_V1_MULTIPROCESSING"] = "0"
            os.environ["RANK"] = "0"
            os.environ["LOCAL_RANK"] = "0"
            os.environ["WORLD_SIZE"] = "1"
            os.environ["MASTER_ADDR"] = "localhost"
            os.environ["MASTER_PORT"] = "29500"

        def save_model(self, d):
            Path(d).mkdir(parents=True, exist_ok=True)

    run_grpo(_spec(tmp_path, ANSWER_STOP), trainer_factory=lambda **kw: Trainer(**kw))
    assert log == ["shutdown"]
    for key in ("VLLM_ENABLE_V1_MULTIPROCESSING", "RANK", "LOCAL_RANK", "WORLD_SIZE",
                "MASTER_PORT"):
        assert key not in os.environ, key
    assert os.environ["MASTER_ADDR"] == "node7"


def test_run_grpo_restores_the_environment_when_training_fails(tmp_path, monkeypatch):
    monkeypatch.delenv("VLLM_ENABLE_V1_MULTIPROCESSING", raising=False)

    class Trainer:
        model = None

        def train(self):
            os.environ["VLLM_ENABLE_V1_MULTIPROCESSING"] = "0"
            raise RuntimeError("boom")

    with pytest.raises(RuntimeError, match="boom"):
        run_grpo(_spec(tmp_path, ANSWER_STOP), trainer_factory=lambda **kw: Trainer())
    assert "VLLM_ENABLE_V1_MULTIPROCESSING" not in os.environ


def _run_with_completions(tmp_path, stop, completions):
    class Trainer:
        def __init__(self, **kw):
            self.model = None
            self.reward_funcs = kw["reward_funcs"]

        def train(self):
            self.reward_funcs[0](completions=completions, prompts=["p0"] * len(completions))

        def save_model(self, d):
            Path(d).mkdir(parents=True, exist_ok=True)

    spec = GRPOSpec(
        model_path="m", model_key="k", items=_items(), verify_fn=lambda i, c: True,
        max_steps=1, num_generations=2, learning_rate=1e-6, beta=0.04,
        temperature=1.0, seed=0, output_dir=str(tmp_path / "out"), save_steps=None,
        stop=stop,
    )
    run_grpo(spec, trainer_factory=lambda **kw: Trainer(**kw))
    return json.loads((tmp_path / "out" / "run_manifest.json").read_text())


def test_manifest_records_the_generation_backend_and_stop(tmp_path):
    m = _run_with_completions(tmp_path, ANSWER_STOP, ["a</answer>", "b</answer>"])
    assert m["generation_backend"] == GENERATION_BACKEND == "vllm_colocate"
    assert m["generation_stop"] == "</answer>"
    assert m["include_stop_str_in_output"] is True
    assert m["completion_stop"] == "</answer>"
    assert m["vllm_gpu_memory_utilization"] == 0.3
    assert m["vllm_enable_sleep_mode"] is True
    assert m["vllm_max_model_length"] == 2048
    assert m["vllm_importance_sampling_correction"] is False
    assert "generation_runs_to_cap" not in m


def test_manifest_records_no_stop_for_gsm8k(tmp_path):
    m = _run_with_completions(tmp_path, None, ["7", "8"])
    assert m["generation_backend"] == "vllm_colocate"
    assert m["generation_stop"] is None
    assert m["include_stop_str_in_output"] is False
    assert m["completion_stats"]["n_completions"] == 2
    assert m["completion_stats"]["n_with_stop"] is None
    assert m["completion_stats"]["max_chars_after_first_stop"] is None


def test_manifest_completion_stats_show_whether_generation_stopped(tmp_path):
    # The GPU smoke reads these: with a real generation stop, nothing (beyond a
    # few characters of the token that closed the tag) follows the first stop.
    m = _run_with_completions(
        tmp_path, ANSWER_STOP,
        ["<answer>1</answer>", "<answer>2</answer>\n<think>loop</think>", "no tag", "x"],
    )
    s = m["completion_stats"]
    assert s["n_completions"] == 4
    assert s["n_with_stop"] == 2
    assert s["max_chars_after_first_stop"] == len("\n<think>loop</think>")
    assert s["mean_chars"] == pytest.approx(
        (len("<answer>1</answer>") + len("<answer>2</answer>\n<think>loop</think>") + 6 + 1) / 4
    )
